implement equality testing with explicit error margin (#67)
https://github.com/Mikolaj/horde-ad/pull/67

Implements fp-equality testing with the error margin explicitly passed as a parameter from the caller. For example:

```haskell
testFoo :: Assertion
testFoo =
  assertEqualUpToEpsilon (1e-10 :: Double)
    (rev foo (1.1, 2.2, 3.3) :: (Double,Double,Double))
    (2.4396285219055063, -1.953374825727421, 0.9654825811012627)
```

This enables us to specify different error margins for different comparisons. If you want to keep it simple, you can still rely on the default error margin specified on the command line using `--eq-epsilon`. In that case, you can use the binary `@?~` operator:

```haskell
res @?~ ([3.5e-44,3.5e-44],5.0 :: Float)
```

This also improves error messages in accordance with https://github.com/Mikolaj/horde-ad/issues/70 .

Fixes: https://github.com/Mikolaj/horde-ad/issues/65 and https://github.com/Mikolaj/horde-ad/issues/70 .

List of commits before squash:

* implement assertEqualUpToEps

* implement assertEqualUpToEps3

* implement assertEqualUpToEpsList

* improve type signature

* whitespace fix (indentation)

* get rid of redundant type constraint

* get rid of assertEqualUpToEpsD

* improve assertion messages

* simplify using hlint

* remove unused code

* rewrite assertEqualUpToEpsS

* Revert "rewrite assertEqualUpToEpsS"

This reverts commit db961e6bbcec4c1ef873098579a4274f677f929f.

* rewrite assertEqualUpToEpsS (this time works with @)

* whitespace fix

* port assertEqualUpToEpsS

* port assertEqualUpToEpsVF

* rename assertEqualUpToEpsS1 and assertEqualUpToEpsS

* get rid of assertEqualUpToEpsVF (unused)

* reorganize file

* implement AssertEqualUpToEpsilon class together with 1 instance

* implement instance for pairs

* implement instance for triples

* implement instance for Traversable

* implement instance for Data.Vector.Storable.Vector

* rewrite assert_list

* implement assert_shape

* implement instance for OS.Array

* get rid of: assertEqualUpToEps, assertEqualUpToEps3, assertEqualUpToEpsList

* whitespace fix

* get rid of assertEqualUpToEps

* get rid of assertEqualUpToEpsShape1 (does not compile)

test/common/TestSingleGradient.hs:562:27: error:
    • Expected a type, but
      ‘'[2, 3, 337]’ has kind
      ‘[GHC.Num.Natural.Natural]’
    • In the type ‘'[2, 3, 337]’
      In the expression:
        assertEqualUpToEpsilon
          @'[2, 3, 337] (1e-12 :: Double)
          (bar_3_75
             (1.1, OS.constant 17.3, [OS.constant 2.4, OS.constant 3.6]))
          (OS.constant 46.2)
      In an equation for ‘testBarV’:
          testBarV
            = assertEqualUpToEpsilon
                @'[2, 3, 337] (1e-12 :: Double)
                (bar_3_75
                   (1.1, OS.constant 17.3, [OS.constant 2.4, OS.constant 3.6]))
                (OS.constant 46.2)
    |
562 |   assertEqualUpToEpsilon @'[2, 3, 337] (1e-12 :: Double)
    |                           ^^^^^^^^^^^^

* fix typing error (by Mikolaj)

* get rid of assertEqualUpToEpsShape4

* get rid of assertEqualUpToEpsList

* hlint cleanup

* get rid of forall

* relax type constraint

* relax type constraints

* get rid of AssertClose class

* get rid of assertClose function

* rename asList to as_list

* get rid of assert_close fun

* rename assertEqualUpToEps to assert_close_eps

* get rid of OVERLAPPABLE

* restore 1x OVERLAPPABLE

* implement AssertEqualUpToEpsilon instance for Numeric.LinearAlgebra.Matrix

* implement AssertEqualUpToEpsilon instance for Data.Array.DynamicS.Array

* implement HasShape and Linearizable classes

* add 2 new instances

* implement assertClose

more convenient for visible type application than the binary operator (@?~)

* get rid of MultiParamTypeClasses

* get rid of OVERLAPPABLE

* get rid of OVERLAPPABLE

* simplify

* weaken the constraint

* simplify away Foldable (but see TODO)

* Revert "simplify away Foldable (but see TODO)"

This reverts commit 2b72ee0fba5071f648dd0089f9ddc5639669e719.

* improve help message for the user (--eq-epsilon)

Before:

  --eq-epsilon ARG         Epsilon to use for floating point comparisons:
                           abs(a-b) < epsilon . Default: 1 % 1000000

After:

  --eq-epsilon ARG         Epsilon to use for floating point comparisons:
                           abs(a-b) < epsilon . Default: 1.0e-6

* get rid of AssertEqualUpToEpsilon instances for Foldable and VS.Vector; get rid of OVERLAPPABLE

* implement 2 extra instances

* add OVERLAPPABLE to silent down compile error

* more informative error messages (print out asserted values in full)

We are now getting error messages like:

$ cabal test shortTestForCI --enable-optimization --test-options='--eq-epsilon 0.00000000000000000001 -p "/feedbackAR 3 0 0 3 5.0e-2/"'
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - horde-ad-0.1.0.0 (lib) (configuration changed)
 - horde-ad-0.1.0.0 (lib:testLibrary) (configuration changed)
 - horde-ad-0.1.0.0 (test:shortTestForCI) (configuration changed)
Configuring library for horde-ad-0.1.0.0..
Preprocessing library for horde-ad-0.1.0.0..
Building library for horde-ad-0.1.0.0..
Configuring library 'testLibrary' for horde-ad-0.1.0.0..
Preprocessing library 'testLibrary' for horde-ad-0.1.0.0..
Building library 'testLibrary' for horde-ad-0.1.0.0..
Configuring test suite 'shortTestForCI' for horde-ad-0.1.0.0..
Preprocessing test suite 'shortTestForCI' for horde-ad-0.1.0.0..
Building test suite 'shortTestForCI' for horde-ad-0.1.0.0..
Running 1 test suites...
Test suite shortTestForCI: RUNNING...
Short tests for CI
  Sine RNN tests
    feedbackAR 3 0 0 3 5.0e-2: FAIL (0.07s)
      test/common/TestCommonEqEpsilon.hs:128:
      expected: -0.24868988719256901
       but got: -0.2486898871925689
       (maximum margin of error: 1.0e-20)
      Expected: [-0.9980267284282716,-0.9510565162972417,-0.8443279255081759,-0.6845471059406962,-0.48175367412103653,-0.24868988719256901,-3.673766846290505e-11,0.24868988711894977,0.4817536740469978,0.6845471058659982,0.8443279254326351,0.9510565162207472,0.9980267283507953,0.9822872506502898,0.9048270523889208,0.7705132427021685,0.5877852522243431,0.3681245526237731,0.12533323351198067,-0.1253332336071494,-0.36812455271766376,-0.5877852523157643,-0.7705132427900961,-0.9048270524725681,-0.9822872507291605,-0.9980267284247174,-0.9510565162898851,-0.844327925497479,-0.6845471059273313,-0.48175367410584324]
       but got: [-0.9980267284282716,-0.9510565162972417,-0.8443279255081759,-0.6845471059406962,-0.48175367412103653,-0.2486898871925689,-3.6737446418300124e-11,0.2486898871189501,0.4817536740469982,0.6845471058659988,0.8443279254326359,0.9510565162207482,0.9980267283507965,0.9822872506502912,0.9048270523889225,0.7705132427021704,0.5877852522243452,0.3681245526237752,0.12533323351198278,-0.1253332336071474,-0.368124552717662,-0.5877852523157627,-0.770513242790095,-0.9048270524725675,-0.9822872507291602,-0.9980267284247176,-0.9510565162898857,-0.8443279254974801,-0.6845471059273328,-0.48175367410584524]

That is, the values used in the (failed) assertion are printed out in their entirety (and not just the failed elements).

* simplify assertEqualUpToEpsilonWithMsg for Data.Array.ShapedS.Array

Array shape is encoded in type, so both shapes are equal.

* fix the module export list notation

* use Foldable.toList instead of our own function

* remove unused instance

* make fp comparison non-strict

* move go_assert_list function inside assert_list

* improve help message

* simplify

* generate more tuples (up to 10)

* improve assertion error printing

This is to get rid of confusing error messages like:

Short tests for CI
  Dumb MNIST tests
    first 100 trainset samples only 250 209310 2.0e-2: FAIL (5.65s)
      test/common/TestCommonEqEpsilon.hs:127:
      expected: 3.233123290489956
       but got: 3.2331232904899556
       (maximum margin of error: 1.0e-20)
      Expected: 3.233123290489956
       but got: 3.2331232904899556

instead we now have:

Short tests for CI
  Dumb MNIST tests
    first 100 trainset samples only 250 209310 2.0e-2: FAIL (5.40s)
      test/common/TestCommonEqEpsilon.hs:130:
      expected: 3.233123290489956
       but got: 3.2331232904899556
       (maximum margin of error: 1.0e-20)

but if the data structure is more complex then we continue to print it in full:

Short tests for CI
  Sine RNN tests
    feedbackAR 3 0 0 3 5.0e-2: FAIL (0.08s)
      test/common/TestCommonEqEpsilon.hs:130:
      expected: -0.24868988719256901
       but got: -0.2486898871925689
       (maximum margin of error: 1.0e-20)
      Expected: [-0.9980267284282716,-0.9510565162972417,-0.8443279255081759,-0.6845471059406962,-0.48175367412103653,-0.24868988719256901,-3.673766846290505e-11,0.24868988711894977,0.4817536740469978,0.6845471058659982,0.8443279254326351,0.9510565162207472,0.9980267283507953,0.9822872506502898,0.9048270523889208,0.7705132427021685,0.5877852522243431,0.3681245526237731,0.12533323351198067,-0.1253332336071494,-0.36812455271766376,-0.5877852523157643,-0.7705132427900961,-0.9048270524725681,-0.9822872507291605,-0.9980267284247174,-0.9510565162898851,-0.844327925497479,-0.6845471059273313,-0.48175367410584324]
       but got: [-0.9980267284282716,-0.9510565162972417,-0.8443279255081759,-0.6845471059406962,-0.48175367412103653,-0.2486898871925689,-3.6737446418300124e-11,0.2486898871189501,0.4817536740469982,0.6845471058659988,0.8443279254326359,0.9510565162207482,0.9980267283507965,0.9822872506502912,0.9048270523889225,0.7705132427021704,0.5877852522243452,0.3681245526237752,0.12533323351198278,-0.1253332336071474,-0.368124552717662,-0.5877852523157627,-0.770513242790095,-0.9048270524725675,-0.9822872507291602,-0.9980267284247176,-0.9510565162898857,-0.8443279254974801,-0.6845471059273328,-0.48175367410584524]

* get rid of Cabal dependency

* hlint clean